version: '3'
services:
  spkz-node:
    build:
      context: ./
      dockerfile: Dockerfile.local
    image: spkz-node
    container_name: spkz-node
    volumes:
      - ./:/home/api
    environment:
      - DB_NAME=spkz-node
      - DB_USER=spkz
      - DB_PASSWORD=spkz
      - DB_HOST=postgres-spkz-node
      - DB_PORT=5432
      - DB_SCHEMA=public
      - DB_LOGGING=false
      - DEBUG=true
      - NODE_ENV=development
      - CONTEXT_PATH=
      - PORT=3000
      - NETWORK_ID=80001
      - CHAIN_ID=80001
      - REDIS_URL=redis://redis-ws:6379
      - spkzEnv=test
    ports:
      - 3000:3000
    depends_on:
      - redis-ws
      - postgres-spkz-node
  postgres-spkz-node:
    image: postgres:13.4
    container_name: postgres-spkz-node
    volumes:
      - postgres-volume-spkz-node:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=spkz
      - POSTGRES_PASSWORD=spkz
      - POSTGRES_DB=spkz-node
    ports:
      - 5432:5432
  redis-ws:
    image: redis
    container_name: redis-ws
  spkz-notification:
    build:
      context: ./
      dockerfile: Dockerfile.websocket.local
    image: spkz-notification
    container_name: spkz-notification
    environment:
      - REDIS_URL=redis://redis-ws:6379
      - spkzEnv=test
    volumes:
      - ./:/home/api
    ports:
      - 3001:3001
    depends_on:
      - redis-ws
  spkz-push-notification:
    build:
      context: ./
      dockerfile: Dockerfile.pushNotification.local
    image: spkz-push-notification
    container_name: spkz-push-notification
    environment:
      - REDIS_URL=redis://redis-ws:6379
      - spkzEnv=test
      - DB_NAME=spkz-node
      - DB_USER=spkz
      - DB_PASSWORD=spkz
      - DB_HOST=postgres-spkz-node
      - DB_PORT=5432
      - DB_SCHEMA=public
      - DB_LOGGING=false
    volumes:
      - ./:/home/api
    depends_on:
      - redis-ws
      - postgres-spkz-node
volumes:
  postgres-volume-spkz-node:
